# Generated by Django 5.2.2 on 2025-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
